version: '3.8'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  app:
    build:
      context: ./myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=myuser
      - PGDATABASE=mydatabase
      - PGPASSWORD=mypassword
      - PGPORT=5432

# docker-compose up --build  создать контейнер
# docker-compose start  запустить контейнер
# docker-compose stop  остановить контейнер
# docker-compose down  удалить контейнер